// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpD_ES2IMDRGXcxc8HVexcR8wI1LUCwxs',
    appId: '1:975791479162:web:cf1d0b34d6b2061b5f5ec3',
    messagingSenderId: '975791479162',
    projectId: 'cryptolistapp-bbeda',
    authDomain: 'cryptolistapp-bbeda.firebaseapp.com',
    storageBucket: 'cryptolistapp-bbeda.appspot.com',
    measurementId: 'G-YYDS45L0M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIdVCjH7dvQENSp9Nrb-fN3oe9R29afpU',
    appId: '1:975791479162:android:85154ce48868ebda5f5ec3',
    messagingSenderId: '975791479162',
    projectId: 'cryptolistapp-bbeda',
    storageBucket: 'cryptolistapp-bbeda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRmL5t_80SUoJlSQUUaCiHTQLooMl1rHo',
    appId: '1:975791479162:ios:d2eb809393a3ff475f5ec3',
    messagingSenderId: '975791479162',
    projectId: 'cryptolistapp-bbeda',
    storageBucket: 'cryptolistapp-bbeda.appspot.com',
    iosBundleId: 'com.example.cryptoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRmL5t_80SUoJlSQUUaCiHTQLooMl1rHo',
    appId: '1:975791479162:ios:d2eb809393a3ff475f5ec3',
    messagingSenderId: '975791479162',
    projectId: 'cryptolistapp-bbeda',
    storageBucket: 'cryptolistapp-bbeda.appspot.com',
    iosBundleId: 'com.example.cryptoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpD_ES2IMDRGXcxc8HVexcR8wI1LUCwxs',
    appId: '1:975791479162:web:c6a1ba4ff3b521065f5ec3',
    messagingSenderId: '975791479162',
    projectId: 'cryptolistapp-bbeda',
    authDomain: 'cryptolistapp-bbeda.firebaseapp.com',
    storageBucket: 'cryptolistapp-bbeda.appspot.com',
    measurementId: 'G-NJD3QNY2ED',
  );

}